### ISSUE TITLE
Error reported with Deployable zip

### ISSUE THREAD

**Issue by BobLies** [oracle-devrel/terraform-oci-arch-oac-heatwave#7]
When I try to use the Deploy button to auto-deploy the code to RM, the following error is reported:

(400, InvalidParameter, false) javax.net.ssl.SSLException: Unsupported or unrecognized SSL message (opc-request-id: csid1bc3f7e944af8c10a112e70db959/9a82201989054052aad41d64b121708a/D472AC941F5B810516848227C3AD64B1) Request ID: csid1bc3f7e944af8c10a112e70db959/9a82201989054052aad41d64b121708a/3E2FB6745E4C60AC855ECD8539970EBC. Timestamp: Mon, Aug 29, 2022, 16:31:22 UTC. Endpoint: https://cloud.oracle.com/stacks/create. Error code: InvalidParameter(400).

**Comment by lfeldman** [comment]
This is RMS internal error which is now escalated. I will keep you posted.

**Comment by lfeldman** [comment]
Issue has been fixed by RMS team.
